language: ruby
cache:
  bundler: true
  apt: true
rvm:
- 2.2.2
bundler_args: "--without data"
branches:
  only:
  - master
env:
  matrix:
  - BUILD_LANG=cs
  - BUILD_LANG=en
  global:
  - secure: aCCb45GaB75AtaKLT9sYaVeteV3V7njXz5CgD4+mgbDKAYXhcwkaC2xwq8ZwZNw4nMt8gbgd6vFqOUCE+RoBd6UFhU7e2ryPsBTYvltRXPzBwVHzq3ElmsDIAzHRFNsQaJSDE8+OFUwxnwP+6Kzle9boMf9ffaBaxe/6V533sfU=
  - secure: bYBZteQLMzKmiDkXRmUsFxnrTpC80WQrgfjGYjixtsGjombg+O71ZF/hoec4egwvsAFuwekUx2eOjJ1Y+NjVNYdPHaWkUWKPjAqCMYR+U3RfVh8hV3LAh+cw/0GV381YALWS+TSu04Y/BXZJXf712v2I9c8MPNLoydOKPs3DSIQ=
  - secure: e1IWdn37+yLU229MRul4zw+50x1hRIXWcsFne8kgShH/mLqSpf5jj0xQ0NpmeAjNUh5dj7uYHFkPp846BqArwy8mURhKuLGsZ8AOCPFKH4E76KiDumh0yo4igEXhHY5dtaW9tMBr6yWiXwoe0MdV57Pt/ImemNSYe+hPVVYeSVQ=
before_script:
- sudo apt-get install lftp
- echo "set ssl:verify-certificate no" >> ~/.lftprc
script: middleman deploy
