sudo: false
dist: trusty
cache:
  bundler: true
  apt: true
  directories:
  - build/
addons:
  apt:
    packages:
    - lftp
rvm:
- 2.4
bundler_args: "--without data development"
branches:
  only:
  - master
  - 2017
env:
  matrix:
  - BUILD_LANG=cs DEPLOY_PATH='cz/2017'
  - BUILD_LANG=en DEPLOY_PATH='eu/2017'
  - BUILD_LANG=''
script:
  - bundle exec middleman build --verbose
before_deploy:
  - echo "set ssl:verify-certificate no" >> ~/.lftprc
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    local_dir: build
    on:
      branch: master
      condition: $BUILD_LANG = ''
  - provider: script
    script: script/deploy
    skip_cleanup: true
    on:
      branch: 2017
      condition: "! -z $BUILD_LANG"

