#!/usr/bin/env bash
set -euo pipefail

if [ -z "$BUILD_LANG" ]; then
  echo "BUILD_LANG not set, exiting"
  exit 1
fi

if [ -z "$DEPLOY_TARGET" ]; then
  echo "DEPLOY_TARGET not set, exiting"
  exit 2
fi

if [ -z "$DEPLOY_PATH" ]; then
  echo "DEPLOY_PATH not set (should correspond to tld/year), exiting"
  exit 2
fi

if [[ $DEPLOY_PATH != *"/"* ]]; then
  echo "DEPLOY_PATH does not contain '/'; perhaps you forgot to add subfolder for year?"
  exit 3
fi

build_dir="build"

if [ ! -d "$build_dir" ]; then
  echo "Build directory $build_dir does not exist, exiting"
  exit 4
fi


lftp_cmd="mirror --reverse --verbose --delete $build_dir $DEPLOY_PATH; quit"
lftp -e "$lftp_cmd" "$DEPLOY_TARGET"
